<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class NumberPortaingDu extends Model
{
    protected $fillable = [

        'title',
     'language',
     'subscription',
      'name',
       'f_name',
        'street',
         'no',
          'box',
           'town',
            'postal_code',
             'country',
              'mail',
               'id_card_no',
                'phone_number',
                 'company_name',
                  'legal_status',
                   'client_num',
                    'company_num',
                     'authorized_represent',
                      'old_prepaid_subscription_1',
                       'code_mobile_1',
                        'num_mobile_1',
                        'voice_1',
                         'data_1',
                          'sim_card_1',
                           'customer_no_1',
                            'new_prepaid_subscription_1',
                             'temp_mobile_no_1',
                               'chosen_formula_1',
                                'new_sim_card_1',
                                 'text_1',
                                  'old_prepaid_subscription_2',
                                   'code_mobile_2',
                                    'num_mobile_2',
                                     'voice_2',
                                      'data_2',
                                       'sim_card_2',
                                        'customer_no_2',
                                         'new_prepaid_subscription_2',
                                          'temp_mobile_no_2',
                                           'chosen_formula_2',
                                            'new_sim_card_2',
                                             'text_2',
                                              'old_prepaid_subscription_3',
                                               'code_mobile_3',
                                                'num_mobile_3',
                                                 'voice_3',
                                                  'data_3',
                                                   'sim_card_3',
                                                    'customer_no_3',
                                                     'new_prepaid_subscription_3',
                                                      'temp_mobile_no_3',
                                                       'new_sim_card_3',
                                                       'chosen_formula_3',
                                                        'text_3',
                                                         'copies',
                                                          'date',
                                                          'customer_sig'];
}
